platform :ios, '12.0'
inhibit_all_warnings!

def linter
  pod 'SwiftLint', '0.29.1'
end

target 'Lyb' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Lyb
  linter

  target 'LybTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LybUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Networking' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Networking
  linter

  target 'NetworkingTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
